# Generated by Django 4.1.3 on 2022-11-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_candidatesapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesapplied',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='candidatesapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadidatesapplied', to='job.job'),
        ),
    ]
